### ISSUE TITLE
希望添加Readme.md和licence文件。

### ISSUE THREAD

**Issue by hstarorg** [i66soft/osharp.v2#1]
添加Readme文件，方便一目了然整个项目的作用。
添加licence文件，也是开源项目很关键的一点。

**Comment by gmf520** [comment]
好，还没玩明白，创建项目的时候跳过了，后面就不知道怎么添加了，是不是签入文件即可

**Comment by terwer** [comment]
直接添加这两个文件提交就行了。
LICENSE
README.md
可以参考下我的模板
https://github.com/terwer/commons4net/blob/master/LICENSE
https://raw.githubusercontent.com/terwer/commons4net/master/README.md

**Comment by hstarorg** [comment]
对的，楼上的方式即可。

**Comment by hstarorg** [comment]
issue处理了需要关闭哦~
