### ISSUE TITLE
代码中注释有“郭明锋”，这个项目是博客园的郭明锋写的吗？

### ISSUE THREAD

**Issue by tiger2014** [i66soft/osharp.v2#17]

**Comment by tiger2014** [comment]
第一次运行出现这个异常：
异常详细信息: System.ComponentModel.Win32Exception: 系统找不到指定的文件。

源错误: 

行 55:  
行 56:             //EF预热，解决EF6第一次加载慢的问题
行 57:             ObjectContext objectContext = ((IObjectContextAdapter)context).ObjectContext;
行 58:             StorageMappingItemCollection mappingItemCollection = (StorageMappingItemCollection)objectContext.ObjectStateManager
行 59:                 .MetadataWorkspace.GetItemCollection(DataSpace.CSSpace);

源文件: h:\osharp\src\OSharp.Core.Data.Entity\DatabaseInitializer.cs    行: 57

**Comment by gmf520** [comment]
是的，同一个人

**Comment by JosonJiang** [comment]
肯定是了
