### ISSUE TITLE
分页扩展的建议

### ISSUE THREAD

**Issue by wudiliujie** [i66soft/osharp.v2#3]
SortCondition[] sort = new SortCondition[] { new SortCondition("CreatedTime", ListSortDirection.Descending) };

CreatedTime 不是强类型的，希望楼主修改成Func,这样可以写起来更方便，因为分页查询的时候都需要排序的。

**Comment by gmf520** [comment]
这个似乎不是很好改，因为不仅仅是需要属性名，还需要与之对应的排序方式ListSortDirection

**Comment by gmf520** [comment]
OK，思考了一下，仅仅第一个参数CreatedTime使用Func应该是没问题的，可能就变成如下的方式了：
    SortCondition[] sort = new SortCondition[] { new SortCondition(m=>m.CreatedTime, ListSortDirection.Descending) };

**Comment by gmf520** [comment]
https://github.com/i66soft/osharp/commit/57f14b35807d2e019c12cf4bb807ae237967d05a#diff-f9ecc326525723afa3b4715f97a31686R50
已添加，欢迎审阅
